language: php
php:
- '7.3'
env:
  global:
  - ZIP_FILENAME=wpdm-na-customizations${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
jobs:
  include:
  - stage: lint
    script:
    - echo 'done'
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=wpdm-na-customizations.zip
    - PLUGIN="wpdm-na-customizations"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*"
      -x "*assets*" -x "composer.*" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
notifications:
  slack:
    secure: X99q0tRkx6b+igdA54zqOWPVeujLVohbGTdbYGXAtypFhzrZ/v12nNW6QMARvx7i9+LifRgcCzIdnw0DtVi4G5FCxbA9sdUKBpAWAxpzklhhNIDyIS8PMhARxylZb3aB9ie5UWeblwVt9PeOfwd4F8Fz25ZMME8UkDkRJS0kymXzmGj7Jm5k+C7TqMmxK9LkB42Iby9btC0MjLFtIHsaEHrflCvP1U8Gc0gfeazg2aRJPLLrACj5ObGpFLQ0xxBCfzTxS64AjWozO7zTYZu+6YKtUdsEMKHf5wh6MG1TyBb0OBC7CJNPf4ULbmmP+/Pjn2Gylva77/ElGSZJcOXKDaMGhFtmxtN9/ZhoSLZ+ntMccWkTdqePb14xs6uQifj2Qi4r9SiIf/aeED2DURdzDynJaH17QE+KxQ2hdH/L3xkPByqG0Px/O61Gpcwc8ng29tsns4tWMh+FGv3rShXWUUnyisfQhHlw+2aAHlqubDkt/4m3CluazwIH2lliz0HNUXfrs2rOaNT0vdKmYe1fKJDGsMvQG49xwIZKSKVUmRqNVzHCgz8v/ZfvVl15eq2Uzv+8vmo524YRLAzFyiReBMQRfrNts1fE/hwOEXLEwDrnMOYnzb9nMM9w9EHTbcpu638I4hRlhwzYLEtdZh9MkBBfz27jhdhrs9g2RynXhg4=
  email: false
deploy:
  provider: releases
  api_key:
    secure: jV9asYo3b51MZpGuLVzXHARnHOR0H8c+sRBXme17tqOb/FThXel35ZGpUFL+y9YZcaS99Jt/sUxDoxSMXy0Z9dV2hJUltaTAQpw9j0cFSBIyXamzMX6+VlKW6R8kyuvnrHjB4JSZvi0zl1zVkHSFwYWT7Peo8xiqczC3OVNBZWlKpWVuShAiHKWaS5bZvuJks1ab918OhWIaH2a6jEZhEeHEnCKGdyg4hYKftbPP2tVMr2b2pqqFkX5mhnSM1VxBf3PznwgUjgAdVj9BBifA0vAw3WK4BCLD7yvILAMHJWf7DNfubsVQq7Bpe26H+LA+Ktkguo7MB9xxkzd+0f1roKkB963hYWb6+hcLrT+K4USCJ4NBgwwz/aANzqpw3VuD8IKoiEC2xEn6iRZWovsqJY5S7jEdjxv2BM05goJczvoXfgQBoKzptGXfdpGBtxV0BRQ8RpD6pSk+8di42W01twNxLyLulnZPE8H/+dilquW/GTxcBeU1+QF76GXTjwcWtUd5s18RUC6NfWEdijEiMlJwB7+lGnFwM8T1ZMwqUMRVKOYvqDbye37NlurCXbDoLqTHn3q93BGizW+VQor97b5L73yI9QZT9ZOMddpZtau80pVeujiI23v5vqoJzhwyQOgya9uB6KTTrsiDjZ39tMCTqXNjPSFI3pUoek7lelw=
  file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
  on: 
    tags: true
  skip_cleanup: 'true'
