language: php
php:
- '7.3'
env:
  global:
  - ZIP_FILENAME=wpdm-na-customizations${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
jobs:
  include:
  - stage: lint
    script:
    - echo 'done'
  - stage: zip file
    env:
    - BUILD_DIR=build
    - DIST_DIR_GITHUB=dist/github
    - GITHUB_RELEASE_FILENAME=wpdm-na-customizations.zip
    - PLUGIN="wpdm-na-customizations"
    script:
    - find ./ -type d | xargs chmod 755
    - find ./ -name '*.php' | xargs chmod 644
    - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*"
      -x "*assets*" -x "composer.*" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
    before_deploy:
    - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
notifications:
  slack:
    secure: yHKo4S3hZ9IDzzto+fMZTCO8WdzwV5LDyjkBPqmWRMhPDXSi/LGybx/iVwc2TeVLCuWXuRLLkg+eue1odI2ACGdzG81aAbovOjX6JFsOLMc23crk6dsmwNaCXmi9R1Ujnb9pUgz1UjPlvwht1HLJBh+Q0n8BeUqfbiVnrpmaT+P1QD42rDMUY41Um31khkQDxDT8g1/gxaY7yHlfcfi36uDjZQCa+X9XTQcJ6LBPjFz0D5R8UTyiD/kaKnoaDHLzroNNtuZTM9An4Bp7bZeNvIUJQEkdTqHJ/xhHbNI/BK4EdVok+tJhaJf5fuH3lU0en0cF5igqlSGp/AdjmYNYLD5NG2hdoSNZpaStrNUoNuJLlE6b8KINOriFpjo55vWOLb56az8EqCKCpy6bztANzwIvyejE+uhoo2cRIvG3sb6xLPtFZ+lE5+9w3AW2HD89x6tCY3ysiL7MfHwPuBa9vx41/rXF0WXoTYG3C3aQC8hkx8E/PiUim437g5fKYMiOd2Dzq/EdMr848wpSUBxP5CAq65RqTpTxaSQ+Rtoi0rWthBUQe14r5cwQojL0aGf02eRZ53Wui17L74gkepg/RNuI7SQeERZEWhb0FiYzc1jcn2BToQ5w/8vSEo89KLtjTUzcutu3AhtriRI5+2H+xp8NOI+YwqjVcvOMBMt1I8w=
    email: false
deploy:
  provider: releases
  api_key:
    secure: jV9asYo3b51MZpGuLVzXHARnHOR0H8c+sRBXme17tqOb/FThXel35ZGpUFL+y9YZcaS99Jt/sUxDoxSMXy0Z9dV2hJUltaTAQpw9j0cFSBIyXamzMX6+VlKW6R8kyuvnrHjB4JSZvi0zl1zVkHSFwYWT7Peo8xiqczC3OVNBZWlKpWVuShAiHKWaS5bZvuJks1ab918OhWIaH2a6jEZhEeHEnCKGdyg4hYKftbPP2tVMr2b2pqqFkX5mhnSM1VxBf3PznwgUjgAdVj9BBifA0vAw3WK4BCLD7yvILAMHJWf7DNfubsVQq7Bpe26H+LA+Ktkguo7MB9xxkzd+0f1roKkB963hYWb6+hcLrT+K4USCJ4NBgwwz/aANzqpw3VuD8IKoiEC2xEn6iRZWovsqJY5S7jEdjxv2BM05goJczvoXfgQBoKzptGXfdpGBtxV0BRQ8RpD6pSk+8di42W01twNxLyLulnZPE8H/+dilquW/GTxcBeU1+QF76GXTjwcWtUd5s18RUC6NfWEdijEiMlJwB7+lGnFwM8T1ZMwqUMRVKOYvqDbye37NlurCXbDoLqTHn3q93BGizW+VQor97b5L73yI9QZT9ZOMddpZtau80pVeujiI23v5vqoJzhwyQOgya9uB6KTTrsiDjZ39tMCTqXNjPSFI3pUoek7lelw=
  file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
  on:
    tags: true
  skip_cleanup: 'true'
